from setuptools import setup, find_packages

setup(
    name="housegan",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "Pillow>=10.0.0,<11.0.0",
        "imageio>=2.30.0",
        "networkx>=3.2",
        "numpy>=1.26.0",
        "scipy>=1.11.0",
        "matplotlib>=3.8.0",
        "scikit-image>=0.21.0",
        "opencv-python>=4.9.0.80",
        "svgwrite>=1.4.3",
        "webcolors>=1.13",
        "pygraphviz>=1.10",
        "torch>=2.1.0",
        "torchvision>=0.16.0",
    ],
    author="Your Name",
    author_email="your.email@example.com",
    description="A powerful machine learning engine for generating realistic house floorplans using GANs",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/housegan",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
    python_requires=">=3.8",
) 